global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'api-gateway'
    dns_sd_configs:
      - names:
          - 'api-gateway'
        type: 'A'
        port: 5000
    metrics_path: '/metrics'
